### ISSUE TITLE
please support desktop

### ISSUE THREAD

**Issue by FlyingYu-Z** [adrielcafe/lyricist#1]
![image](https://user-images.githubusercontent.com/23566361/127105129-02320df4-fd6d-49d0-9058-5322e725c48c.png)

**Comment by adrielcafe** [comment]
Desktop support will come. I'm looking for a way to share code between both compose android/desktop and publish as separete modules.

**Comment by FlyingYu-Z** [comment]
> Desktop support will come. I'm looking for a way to share code between both compose android/desktop and publish as separate modules.

Thank you!

**Comment by adrielcafe** [comment]
FYI [1.1.0](https://github.com/adrielcafe/lyricist/releases/tag/1.1.0) supports desktop :)

**Comment by FlyingYu-Z** [comment]
> FYI [1.1.0](https://github.com/adrielcafe/lyricist/releases/tag/1.1.0) supports desktop :)

Thank you for hard work..
