### ISSUE TITLE
Adding Icon Into The Text

### ISSUE THREAD

**Issue by mehmetakify** [adrielcafe/lyricist#12]
Adding Image or preferably any composable into the text would be great to achieve something like:

Please click [icon] button.

Please click [compsable] button.

**Comment by adrielcafe** [comment]
This feature is outside the context of this library, but fortunately Compose has the [InlineTextContent API](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/InlineTextContent) for that purpose. Please take a look on it.
