### ISSUE TITLE
too many argument Bug

### ISSUE THREAD

**Issue by kazemcodes** [adrielcafe/lyricist#21]
When the xml has too many properties like over 162 this error is throws in jvm
```
Exception in thread "main" java.lang.ClassFormatError: Too many arguments in method signature in class file ireader/i18n/XmlStrings
```
and in android it throws 
```
FATAL EXCEPTION: main
 Process: ir.kazemcodes.infinityreader.debug, PID: 8153
 java.lang.VerifyError: Verifier rejected class ireader.i18n.EnXmlStringsKt: void ireader.i18n.EnXmlStringsKt.<clinit>() failed to verify: void ireader.i18n.EnXmlStringsKt.<clinit>(): [0x539] Rejecting invocation, expected 162 argument registers, method signature has 163 or more (declaration of 'ireader.i18n.EnXmlStringsKt' appears in /data/data/ir.kazemcodes.infinityreader.debug/code_cache/.overlay/base.apk/classes6.dex)
 ```
maybe its because of https://github.com/Kotlin/kotlinx.serialization/issues/1393 and https://github.com/Kotlin/kotlinx.serialization/issues/632

sample project: https://github.com/IReaderorg/IReader/tree/migrate_to_lyrstic

**Comment by kazemcodes** [comment]
I think data class is unsuitable for storing translation

**Comment by adrielcafe** [comment]
On [1.5.0](https://github.com/adrielcafe/lyricist/releases/tag/1.5.0) an interface is used instead of data class. Thanks for reporting this issue!

**Comment by humblerookie** [comment]
I think this issue might even trickle into user defined translations not just xml imports, we should update the samples as well
