### ISSUE TITLE
Java runtime version too high

### ISSUE THREAD

**Issue by Skaldebane** [adrielcafe/lyricist#26]
Hi! I just updated to 1.6.0 from 1.4.2 today, but my project no longer builds anymore.

Apparently in a recent commit you removed the Java 1.8 constraint, and now the library is built and published with Java 19, a non-LTS version of Java. 

This happened to [another library](https://github.com/chrisbanes/material3-windowsizeclass-multiplatform/issues/28) these days as well. While the latest LTS Java release, 21, has been released, it's still very new and may not be available in development environments yet. Consider using Java 17 for now.

**Comment by adrielcafe** [comment]
Ops, fixed on [1.6.1](https://github.com/adrielcafe/lyricist/releases/tag/1.6.1). Thanks for the heads up!
