### ISSUE TITLE
@LyricistStrings can't be internal

### ISSUE THREAD

**Issue by LincolnStuart** [adrielcafe/lyricist#4]
When I try to make my val annoted  with `@LyricistStrings` internal, my app doesn't compile 😕

error:
`'public' property exposes its 'internal' type argument MyModuleToolsStrings`

**Comment by adrielcafe** [comment]
Implemented on [1.2.2](https://github.com/adrielcafe/lyricist/releases/tag/1.2.2). Thanks!
