### ISSUE TITLE
xml <string-array> must end in <resource>?

### ISSUE THREAD

**Issue by jiechic** [adrielcafe/lyricist#5]
![image](https://user-images.githubusercontent.com/518977/179153124-120f6475-7a58-4f63-803b-862f178067ad.png)

**Comment by jiechic** [comment]
> https://developer.android.com/guide/topics/resources/string-resource#StringArray
>Note: An integer array is a simple resource that is referenced using the value provided in the name attribute (not the name of the XML file). As such, you can combine integer array resources with other simple resources in the one XML file, under one <resources> element.

>https://developer.android.com/guide/topics/resources/more-resources#IntegerArray
>Note: A string array is a simple resource that is referenced using the value provided in the name attribute (not the name of the XML file). As such, you can combine string array resources with other simple resources in the one XML file, under one <resources> element.

in xml ,<Resource> should have <string> <string-array> <interger> <interger-array> <dimin> <color> and so on
can you support different element in the <Resource>

**Comment by adrielcafe** [comment]
The provided info was not enough to reproduce. Feel free to reopen the issue with more details or a reproducible sample project.
