### ISSUE TITLE
 Function declaration must have a name

### ISSUE THREAD

**Issue by jiechic** [adrielcafe/lyricist#8]
kotlin 1.7.0

![image](https://user-images.githubusercontent.com/518977/185092456-297ccf9c-7c28-4de0-aca5-e5065e1e2d43.png)

**Comment by DevSrSouza** [comment]
Can you share some code to reproduce it? It still can be reproduce in Kotlin 1.8 @jiechic ?

**Comment by adrielcafe** [comment]
The provided info was not enough to reproduce. Feel free to reopen the issue with more details or a reproducible sample project.
